// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0pZlkv1O7wenKOFH0W8GrNmMX-2t-rdw',
    appId: '1:261531380731:web:f09d9adda3a0d3dea0b95e',
    messagingSenderId: '261531380731',
    projectId: 'e-commerce-app-9de33',
    authDomain: 'e-commerce-app-9de33.firebaseapp.com',
    storageBucket: 'e-commerce-app-9de33.appspot.com',
    measurementId: 'G-BGHRJQNFVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYHfm8iBoueBnxQ1KcJyxmbOubqup6Sus',
    appId: '1:261531380731:android:5c1fc88d9407ec74a0b95e',
    messagingSenderId: '261531380731',
    projectId: 'e-commerce-app-9de33',
    storageBucket: 'e-commerce-app-9de33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvX1UMgVbWKDYnnyjOxxStDTi6tzRNS6A',
    appId: '1:261531380731:ios:d8da03f4cc999377a0b95e',
    messagingSenderId: '261531380731',
    projectId: 'e-commerce-app-9de33',
    storageBucket: 'e-commerce-app-9de33.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvX1UMgVbWKDYnnyjOxxStDTi6tzRNS6A',
    appId: '1:261531380731:ios:d8da03f4cc999377a0b95e',
    messagingSenderId: '261531380731',
    projectId: 'e-commerce-app-9de33',
    storageBucket: 'e-commerce-app-9de33.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0pZlkv1O7wenKOFH0W8GrNmMX-2t-rdw',
    appId: '1:261531380731:web:35e95b56f638d3faa0b95e',
    messagingSenderId: '261531380731',
    projectId: 'e-commerce-app-9de33',
    authDomain: 'e-commerce-app-9de33.firebaseapp.com',
    storageBucket: 'e-commerce-app-9de33.appspot.com',
    measurementId: 'G-0XC5YJWBYG',
  );
}
